version: '3.5'
services:
  server:
    build:
      dockerfile: ./docker/server/Dockerfile
      context: ./
    volumes:
      - ./:/server
    restart: always
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5435:5432
    restart: always
  weavescope:
    image: weaveworks/scope:1.12.0
    restart: always
    ports:
      - 4040:4040
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker"
      - "true"
    environment:
      - ENABLE_BASIC_AUTH=true
      - BASIC_AUTH_USERNAME=${WEAVESCOPE_USER:-admin}
      - BASIC_AUTH_PASSWORD=${WEAVESCOPE_PASSWORD:-admin}
      - TZ=Europe/Moscow
